### ISSUE TITLE
How do I "move" the mandelbrot zoom location?

### ISSUE THREAD

**Issue by Chew** [Demonstrandum/Fractal#1]
I want to zoom in to other parts of the Mandelbrot instead of dead centre, how can I manage this?

Thanks for this gem, appreciate ya.

**Comment by Demonstrandum** [comment]
I'll have to implement that, should be very easy, however I want a nice way of controlling this. 

Sorry I've only noticed this now... :confused:

**Comment by Demonstrandum** [comment]
I'll have a look tomorrow morning. :ok_hand:

**Comment by Chew** [comment]
Thanks!

**Comment by Demonstrandum** [comment]
@Chewsterchew, would you prefer to give your offset in traditional Cartesian form, or as a complex number?

**Comment by Chew** [comment]
Which would be easier?

**Comment by Demonstrandum** [comment]
It works now, with some nice places listed on http://www.cuug.ab.ca/dewara/mandelbrot/Mandelbrowser.html
Take the top two for example,


we can generate:
![close_1](https://user-images.githubusercontent.com/26842759/42823116-a7edc926-89d4-11e8-9000-52b463148a62.png)
made with
```
fractal mandelbrot --offset=-0.7463,0.1102 --scale=0.005 --def=1000 -o=close_1.png
```

and

![close_2](https://user-images.githubusercontent.com/26842759/42823162-c69f8ecc-89d4-11e8-8c96-41e07ea9c067.png)
made with
```
fractal mandelbrot --offset=-0.7453,0.1127 --scale=6.5e-4 --def=1000 -o=close_2.png
```


---

Remeber, the deeper you go, the more you should increase your definition (`--def=1500` for example)

**Comment by Demonstrandum** [comment]
@Chewsterchew They're both as easy, I just went for the more simplistic Cartesian formatting, just need a comma.

**Comment by Chew** [comment]
That's brilliant, how would you do it in colour?

**Comment by Demonstrandum** [comment]
Just add the `--color=multi` argument.

Just (re)download the gem by:
```shell
gem install fractal
```

**Comment by Demonstrandum** [comment]
@Chewsterchew you should be fine to use it now.

**Comment by Demonstrandum** [comment]
if they come out looking a bit bleak and washed, then you can decrease the `def` (num. of iterations per pixel) to give it a bit more colour and depth.

**Comment by Chew** [comment]
Awesome! Can't wait to try it out. Very cool!

**Comment by Demonstrandum** [comment]
@Chewsterchew made a 7000x7000 version of the second example, why not.

https://img42.com/TSGHI

**Comment by Chew** [comment]
Nice! What command did you use to make that?

**Comment by Demonstrandum** [comment]
@Chewsterchew 
```
fractal mandelbrot --offset=-0.7453,0.1127 --scale=6.5e-4 --def=300 -o=close_2.png --color=multi -w=7000 -h=7000
```

It took a _good_ chunk of time.

**Comment by Chew** [comment]
Brilliant! I even put it in my bot

![image](https://user-images.githubusercontent.com/8278263/42968702-a851b7a6-8b69-11e8-9864-3d7b4beadb81.png)

**Comment by Chew** [comment]
Does look a bit washed, I think I set the def to 700 

The image:
![mandel](https://cdn.discordapp.com/attachments/200748039713849351/469257162007511040/469256316804923410.png)

**Comment by Demonstrandum** [comment]
@Chewsterchew Very nice, def=700 must take a while, i think you should be fine with ca. 300 to be honest.

Like that you implemented that functionality to your discord bot!

**Comment by Demonstrandum** [comment]
Also, you might not need the image to be 1080, cut down on time maybe.
